version: '3'
services:
  node_app: # app tudentista
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app
    ports:
      - "4000:4000"
    restart: always
    volumes:
      - ./bot_sessions:/app/bot_sessions
  
  node_app_rimay:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app_rimay
    ports:
      - "4001:4001"
    environment:
      - PORT=4001
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - POSTGRES_DB_HOST=${POSTGRES_DB_HOST}
      - POSTGRES_DB_USER=${POSTGRES_DB_USER}
      - POSTGRES_DB_PASSWORD=${POSTGRES_DB_PASSWORD}
      - POSTGRES_DB_NAME=${POSTGRES_DB_NAME}
      - POSTGRES_DB_PORT${POSTGRES_DB_PORT}
    restart: always
    volumes:
      - ./bot_sessions_rimay:/app_rimay/bot_sessions