# Dockerfile para NGINX
FROM nginx:latest

# Copia el archivo de configuración personalizado de NGINX al contenedor
COPY nginx.conf /etc/nginx/nginx.conf

# Exponer el puerto en el que correrá NGINX
EXPOSE 80
